###Register User
POST http://localhost:2006/auth/users
Content-Type: application/json

{
    "firstName":"author3",
    "lastName":"",
    "email":"author3@gmail.com",
    "password":"author2",
    "role":"AUTHOR",
    "profileImageUrl":"https://example.com/avatars/user.png"
}

###User Login
POST http://localhost:2006/auth/login
Content-Type: application/json

{
    "email":"user1@gmail.com",
    "password":"user13"
}

###User Logout
GET http://localhost:2006/auth/logout

###Change Password
PUT http://localhost:2006/auth/password
Content-Type: application/json

{
    "currentPassword":"user12",
    "newPassword":"user13"
}

### Read articles of all authors
GET  http://localhost:2006/user-api/articles

### Add comment by user 
PUT http://localhost:2006/user-api/article
Content-Type: application/json

{
    "articleId":"69b3ab61b8bc15f7b841fb24",
    "comment":"This is useful article"
}

###Write Article
POST http://localhost:2006/author-api/articles


###Read Article by Author
GET http://localhost:2006/author-api/articles

###Delete Article by ID Soft Delete
PATCH http://localhost:2006/author-api/article
Content-Type: application/json

{
    "articleId":"69b3ab61b8bc15f7b841fb24",
    "isActive": false
}


###Update Article ID
PUT http://localhost:2006/author-api/article
